"""Ingest the generated corpus into ChromaDB.

Reads markdown files from data/corpus/ (generated by scripts/generate_corpus.py),
chunks them using collection-specific strategies, embeds with sentence-transformers,
and stores in the persistent ChromaDB vector store at data/vectorstore/.

Run from the project root:

    python scripts/generate_corpus.py
    python scripts/ingest_corpus.py
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

import logging

from src.config import CORPUS_DIR, VECTORSTORE_DIR
from src.rag.ingest import CorpusIngestor

logging.basicConfig(level=logging.INFO, format="%(levelname)s  %(message)s")
logger = logging.getLogger(__name__)


def main() -> None:
    if not CORPUS_DIR.exists() or not any(CORPUS_DIR.rglob("*.md")):
        logger.error(
            "No corpus files found in %s. Run scripts/generate_corpus.py first.", CORPUS_DIR
        )
        sys.exit(1)

    logger.info("Ingesting corpus from %s", CORPUS_DIR)
    logger.info("Vector store: %s", VECTORSTORE_DIR)

    ingestor = CorpusIngestor()
    counts = ingestor.ingest_all()

    total = sum(counts.values())
    print(f"\nIngestion complete — {total} chunks across {len(counts)} collections:\n")
    for collection, count in counts.items():
        print(f"  {collection:<20} {count} chunks")


if __name__ == "__main__":
    main()
