"""Ingest the generated corpus into ChromaDB.

Reads markdown files from data/corpus/ (generated by scripts/generate_corpus.py),
chunks them using collection-specific strategies, embeds with sentence-transformers,
and stores in the persistent ChromaDB vector store at data/vectorstore/.

Every run is tracked as an MLflow experiment under "radvision/ingestion":
  params : corpus_dir, vectorstore_dir, embedding_model
  metrics: chunks per collection + total

Run from the project root:

    python scripts/generate_corpus.py
    python scripts/ingest_corpus.py

Then open the MLflow UI to inspect the run:

    mlflow ui
"""

import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

import logging

import mlflow

from src.config import CORPUS_DIR, EMBEDDING_MODEL, VECTORSTORE_DIR
from src.rag.ingest import CorpusIngestor
from src.tracking import EXPERIMENT_INGESTION, log_metrics_safe, log_params_safe, set_experiment

logging.basicConfig(level=logging.INFO, format="%(levelname)s  %(message)s")
logger = logging.getLogger(__name__)


def main() -> None:
    if not CORPUS_DIR.exists() or not any(CORPUS_DIR.rglob("*.md")):
        logger.error(
            "No corpus files found in %s. Run scripts/generate_corpus.py first.", CORPUS_DIR
        )
        sys.exit(1)

    logger.info("Ingesting corpus from %s", CORPUS_DIR)
    logger.info("Vector store: %s", VECTORSTORE_DIR)

    set_experiment(EXPERIMENT_INGESTION)
    with mlflow.start_run():
        log_params_safe({
            "corpus_dir": str(CORPUS_DIR),
            "vectorstore_dir": str(VECTORSTORE_DIR),
            "embedding_model": EMBEDDING_MODEL,
        })

        t0 = time.perf_counter()
        ingestor = CorpusIngestor()
        counts = ingestor.ingest_all()
        elapsed = time.perf_counter() - t0

        total = sum(counts.values())
        log_metrics_safe({
            **{f"chunks.{col}": n for col, n in counts.items()},
            "chunks.total": total,
            "ingestion_time_s": round(elapsed, 2),
        })

    print(f"\nIngestion complete — {total} chunks across {len(counts)} collections:\n")
    for collection, count in counts.items():
        print(f"  {collection:<20} {count} chunks")
    print(f"\nIngestion time: {elapsed:.2f}s")
    print("MLflow run logged under experiment:", EXPERIMENT_INGESTION)


if __name__ == "__main__":
    main()
