"""RAG ingestion pipeline for the RadVision Pro support agent.

Loads markdown documents from data/corpus/, splits them into chunks using a
collection-specific strategy, embeds each chunk with sentence-transformers,
and stores everything in ChromaDB.

Chunking strategies per collection:
- kb_articles:   one chunk per H2 section (Symptom / Root Cause / Workaround / Resolution).
                 Each chunk repeats the article header (H1 title + metadata) as a preamble.
- product_docs:  one chunk per H3 subsection (one parameter or scenario per chunk).
                 Each chunk repeats the component name + full Overview section as a preamble.
- release_notes: one chunk per H3 subsection (one feature or known-issue entry per chunk).
                 Each chunk repeats the document title + Release Date / Status as a preamble.

All three strategies embed the repeating preamble so every chunk is self-contained and
retrievable without needing the surrounding document. Estimated chunk sizes are well within
the 512-token limit of the all-MiniLM-L6-v2 embedding model.
"""

import logging
import re
from pathlib import Path

import chromadb
from chromadb.utils.embedding_functions import DefaultEmbeddingFunction

from src.config import CORPUS_DIR, VECTORSTORE_DIR

logger = logging.getLogger(__name__)

# Cosine similarity is standard for sentence-transformers models
_COLLECTION_METADATA = {"hnsw:space": "cosine"}


class CorpusIngestor:
    """Chunks, embeds, and stores corpus documents in ChromaDB.

    Each collection uses a different chunking strategy tailored to the document
    structure generated by scripts/generate_corpus.py.
    """

    def __init__(self, vectorstore_dir: Path = VECTORSTORE_DIR) -> None:
        self._client = chromadb.PersistentClient(path=str(vectorstore_dir))
        # DefaultEmbeddingFunction uses all-MiniLM-L6-v2 via ONNX (no PyTorch needed)
        self._ef = DefaultEmbeddingFunction()
        logger.info("CorpusIngestor ready")

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def ingest_all(self, corpus_dir: Path = CORPUS_DIR) -> dict[str, int]:
        """Ingest all three collections and return chunk counts per collection.

        Args:
            corpus_dir: Root of the generated corpus (data/corpus/).

        Returns:
            Dict mapping collection name to number of chunks stored.
        """
        return {
            "kb_articles": self._ingest_collection(
                corpus_dir / "kb_articles", "kb_articles", self._chunk_kb_article
            ),
            "product_docs": self._ingest_collection(
                corpus_dir / "product_docs", "product_docs", self._chunk_product_doc
            ),
            "release_notes": self._ingest_collection(
                corpus_dir / "release_notes", "release_notes", self._chunk_release_notes
            ),
        }

    # ------------------------------------------------------------------
    # Internal: collection-level ingestion
    # ------------------------------------------------------------------

    def _ingest_collection(self, doc_dir: Path, collection_name: str, chunker) -> int:
        """Chunk all .md files in doc_dir and store in the named collection.

        Always deletes and recreates the collection so stale chunks from previous
        ingestion runs are never mixed with new ones.
        """
        try:
            self._client.delete_collection(collection_name)
        except Exception:
            pass
        collection = self._client.create_collection(
            name=collection_name,
            embedding_function=self._ef,
            metadata=_COLLECTION_METADATA,
        )
        all_chunks: list[dict] = []
        for md_file in sorted(doc_dir.glob("*.md")):
            all_chunks.extend(chunker(md_file))

        if not all_chunks:
            logger.warning("No chunks produced for collection %s", collection_name)
            return 0

        collection.add(
            ids=[c["id"] for c in all_chunks],
            documents=[c["text"] for c in all_chunks],
            metadatas=[c["metadata"] for c in all_chunks],
        )
        logger.info("Ingested %d chunks into '%s'", len(all_chunks), collection_name)
        return len(all_chunks)

    # ------------------------------------------------------------------
    # Chunkers — one per collection
    # ------------------------------------------------------------------

    def _chunk_kb_article(self, path: Path) -> list[dict]:
        """One chunk per H2 section; each chunk repeats the article header.

        Chunk structure:

            {H1 title + metadata block (Article ID, Affected Version, etc.)}

            ## {H2 section name}

            {H2 content — all blocks until the next H2}

        Sections: Symptom / Root Cause / Affected Environments / Workaround /
        Resolution / Related Articles.  The preamble repeats in every chunk so
        each is self-contained and retrievable independently.  Estimated size:
        ~30 tokens (preamble) + ~150-280 tokens (content) = well within 512.
        """
        text = path.read_text(encoding="utf-8")
        kb_id = path.stem
        version = _extract(text, r"\*\*Affected Version:\*\* (.+)")
        component = _extract(text, r"\*\*Affected Components:\*\* (.+)")

        # Preamble = H1 title + all metadata fields before the first ## heading
        preamble = re.split(r"\n## ", text)[0].strip()

        chunks: list[dict] = []
        chunk_index = 0
        current_h2 = ""
        h2_blocks: list[str] = []

        def _emit(h2: str, blocks: list[str]) -> None:
            nonlocal chunk_index
            if not blocks or not h2:
                return
            content = "\n\n".join(blocks)
            chunk_text = f"{preamble}\n\n## {h2}\n\n{content}"
            chunks.append({
                "id": f"{kb_id}_c{chunk_index}",
                "text": chunk_text,
                "metadata": {
                    "source_type": "kb_article",
                    "kb_id": kb_id,
                    "section": h2,
                    "version": version,
                    "component": component,
                    "source_file": path.name,
                    "chunk_index": chunk_index,
                },
            })
            chunk_index += 1

        for block in re.split(r"\n\n+", text):
            block = block.strip()
            if not block:
                continue
            if block.startswith("# "):
                continue
            if block.startswith("## "):
                _emit(current_h2, h2_blocks)
                h2_blocks = []
                current_h2 = block.lstrip("# ").strip()
                continue
            if not current_h2:
                continue   # preamble metadata — already captured
            h2_blocks.append(block)

        _emit(current_h2, h2_blocks)
        return chunks

    def _chunk_product_doc(self, path: Path) -> list[dict]:
        """One chunk per H3 subsection, each prefixed with component name and Overview.

        Chunk structure (plain text, no markdown heading markers):

            {component}

            Overview
            {overview text}

            {H2 section name}
            {H3 subsection name}
            {H3 content — all blocks until the next H3 or H2}

        H2 sections without H3 children (e.g. a GPU requirements table) emit one chunk
        with the H2 content in place of the H3 block.

        The Overview is repeated in every chunk so each chunk is self-contained.
        Estimated token budget: ~80 (overview) + ~200 (content) = ~280 — well within the
        512-token limit of the all-MiniLM-L6-v2 embedding model.
        """
        text = path.read_text(encoding="utf-8")
        component = _first_heading(text)
        overview_text = _extract_section(text, "Overview")

        chunks: list[dict] = []
        chunk_index = 0
        current_h2 = ""
        current_h3 = ""
        h3_blocks: list[str] = []        # content blocks under the current H3
        h2_blocks: list[str] = []        # content blocks under H2 before any H3

        def _emit(h2: str, h3: str, blocks: list[str]) -> None:
            nonlocal chunk_index
            if not blocks or not h2:
                return
            content = "\n\n".join(blocks)
            heading_line = f"{h2}\n{h3}" if h3 else h2
            chunk_text = (
                f"{component}\n\nOverview\n{overview_text}\n\n{heading_line}\n{content}"
            )
            chunks.append({
                "id": f"{path.stem}_c{chunk_index}",
                "text": chunk_text,
                "metadata": {
                    "source_type": "product_doc",
                    "component": component,
                    "section": h2,
                    "subsection": h3,
                    "source_file": path.name,
                    "chunk_index": chunk_index,
                },
            })
            chunk_index += 1

        for block in re.split(r"\n\n+", text):
            block = block.strip()
            if not block:
                continue
            if block.startswith("# "):
                continue
            if block.startswith("## "):
                _emit(current_h2, current_h3, h3_blocks)
                h3_blocks = []
                _emit(current_h2, "", h2_blocks)
                h2_blocks = []
                current_h2 = block.lstrip("# ").strip()
                current_h3 = ""
                if current_h2 == "Overview":
                    current_h2 = ""   # flag: skip content in this section
                continue
            if block.startswith("### "):
                _emit(current_h2, current_h3, h3_blocks)
                h3_blocks = []
                current_h3 = block.lstrip("# ").strip()
                continue
            if not current_h2:
                continue   # overview content — captured via _extract_section
            if current_h3:
                h3_blocks.append(block)
            else:
                h2_blocks.append(block)

        # flush trailing content
        _emit(current_h2, current_h3, h3_blocks)
        _emit(current_h2, "", h2_blocks)

        return chunks

    def _chunk_release_notes(self, path: Path) -> list[dict]:
        """One chunk per H3 subsection; each chunk repeats the document header.

        Chunk structure:

            {full title line + Release Date / Status metadata}

            {H2 section name}
            {H3 subsection name}
            {H3 content — all blocks until the next H3 or H2}

        H2 sections without H3 children (e.g. "No known issues") produce one chunk
        with the H2 content directly.  The preamble (title + metadata) repeats in
        every chunk so each is self-contained.
        """
        text = path.read_text(encoding="utf-8")
        version = _extract(text, r"v(\d+\.\d+(?:\.\d+)?)")

        # Everything before the first ## heading: H1 title + Release Date + Status
        preamble = re.split(r"\n## ", text)[0].strip()

        chunks: list[dict] = []
        chunk_index = 0
        current_h2 = ""
        current_h3 = ""
        h3_blocks: list[str] = []
        h2_blocks: list[str] = []  # H2 content before any H3

        def _emit(h2: str, h3: str, blocks: list[str]) -> None:
            nonlocal chunk_index
            if not blocks or not h2:
                return
            content = "\n\n".join(blocks)
            heading_line = f"{h2}\n{h3}" if h3 else h2
            chunk_text = f"{preamble}\n\n{heading_line}\n{content}"
            chunks.append({
                "id": f"relnotes_{version.replace('.', '_')}_c{chunk_index}",
                "text": chunk_text,
                "metadata": {
                    "source_type": "release_note",
                    "version": version,
                    "section": h2,
                    "subsection": h3,
                    "source_file": path.name,
                    "chunk_index": chunk_index,
                },
            })
            chunk_index += 1

        for block in re.split(r"\n\n+", text):
            block = block.strip()
            if not block:
                continue
            if block.startswith("# "):
                continue
            if block.startswith("## "):
                _emit(current_h2, current_h3, h3_blocks)
                h3_blocks = []
                _emit(current_h2, "", h2_blocks)
                h2_blocks = []
                current_h2 = block.lstrip("# ").strip()
                current_h3 = ""
                continue
            if block.startswith("### "):
                _emit(current_h2, current_h3, h3_blocks)
                h3_blocks = []
                current_h3 = block.lstrip("# ").strip()
                continue
            if not current_h2:
                continue   # preamble blocks — already captured
            if current_h3:
                h3_blocks.append(block)
            else:
                h2_blocks.append(block)

        # flush trailing content
        _emit(current_h2, current_h3, h3_blocks)
        _emit(current_h2, "", h2_blocks)

        return chunks


# ---------------------------------------------------------------------------
# Shared text utilities
# ---------------------------------------------------------------------------

def _first_heading(text: str) -> str:
    """Return the text of the first # heading, or empty string."""
    m = re.search(r"^# (.+)", text, re.MULTILINE)
    return m.group(1).strip() if m else ""


def _extract_section(text: str, section_name: str) -> str:
    """Return the body of a named ## section (everything up to the next ## heading)."""
    parts = re.split(r"\n## ", text)
    for part in parts[1:]:
        lines = part.split("\n", 1)
        if lines[0].strip() == section_name:
            return lines[1].strip() if len(lines) > 1 else ""
    return ""


def _extract(text: str, pattern: str) -> str:
    """Return the first capture group of pattern, or 'unknown'."""
    m = re.search(pattern, text)
    return m.group(1).strip() if m else "unknown"


