"""RAG ingestion pipeline for the RadVision Pro support agent.

Loads markdown documents from data/corpus/, splits them into chunks using a
collection-specific strategy, embeds each chunk with sentence-transformers,
and stores everything in ChromaDB.

Chunking strategies per collection:
- kb_articles:   one chunk per article (whole document); articles are short and cohesive —
                 splitting by section produces fragments too short to embed meaningfully
- product_docs:  split by paragraph; prepend heading hierarchy as context prefix
- release_notes: split by ## section heading (What's New / Known Issues)
- past_tickets:  one chunk per ticket (whole document); tickets are short and cohesive —
                 splitting by section produces fragments too short to embed meaningfully
"""

import logging
import re
from pathlib import Path

import chromadb
from chromadb.utils.embedding_functions import DefaultEmbeddingFunction

from src.config import CORPUS_DIR, VECTORSTORE_DIR

logger = logging.getLogger(__name__)

# Cosine similarity is standard for sentence-transformers models
_COLLECTION_METADATA = {"hnsw:space": "cosine"}


class CorpusIngestor:
    """Chunks, embeds, and stores corpus documents in ChromaDB.

    Each collection uses a different chunking strategy tailored to the document
    structure generated by scripts/generate_corpus.py.
    """

    def __init__(self, vectorstore_dir: Path = VECTORSTORE_DIR) -> None:
        self._client = chromadb.PersistentClient(path=str(vectorstore_dir))
        # DefaultEmbeddingFunction uses all-MiniLM-L6-v2 via ONNX (no PyTorch needed)
        self._ef = DefaultEmbeddingFunction()
        logger.info("CorpusIngestor ready")

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def ingest_all(self, corpus_dir: Path = CORPUS_DIR) -> dict[str, int]:
        """Ingest all four collections and return chunk counts per collection.

        Args:
            corpus_dir: Root of the generated corpus (data/corpus/).

        Returns:
            Dict mapping collection name to number of chunks stored.
        """
        return {
            "kb_articles": self._ingest_collection(
                corpus_dir / "kb_articles", "kb_articles", self._chunk_kb_article
            ),
            "product_docs": self._ingest_collection(
                corpus_dir / "product_docs", "product_docs", self._chunk_product_doc
            ),
            "release_notes": self._ingest_collection(
                corpus_dir / "release_notes", "release_notes", self._chunk_release_notes
            ),
            "past_tickets": self._ingest_collection(
                corpus_dir / "past_tickets", "past_tickets", self._chunk_past_ticket
            ),
        }

    # ------------------------------------------------------------------
    # Internal: collection-level ingestion
    # ------------------------------------------------------------------

    def _ingest_collection(self, doc_dir: Path, collection_name: str, chunker) -> int:
        """Chunk all .md files in doc_dir and store in the named collection.

        Always deletes and recreates the collection so stale chunks from previous
        ingestion runs are never mixed with new ones.
        """
        try:
            self._client.delete_collection(collection_name)
        except Exception:
            pass
        collection = self._client.create_collection(
            name=collection_name,
            embedding_function=self._ef,
            metadata=_COLLECTION_METADATA,
        )
        all_chunks: list[dict] = []
        for md_file in sorted(doc_dir.glob("*.md")):
            all_chunks.extend(chunker(md_file))

        if not all_chunks:
            logger.warning("No chunks produced for collection %s", collection_name)
            return 0

        collection.add(
            ids=[c["id"] for c in all_chunks],
            documents=[c["text"] for c in all_chunks],
            metadatas=[c["metadata"] for c in all_chunks],
        )
        logger.info("Ingested %d chunks into '%s'", len(all_chunks), collection_name)
        return len(all_chunks)

    # ------------------------------------------------------------------
    # Chunkers — one per collection
    # ------------------------------------------------------------------

    def _chunk_kb_article(self, path: Path) -> list[dict]:
        """Store each KB article as a single chunk.

        KB articles are short by design (4 sections of 1-2 sentences each, ~300-600 chars
        total) and cover exactly one issue. Splitting by section produces fragments that are
        too short to embed meaningfully and loses the connection between symptom, root cause,
        and workaround. The whole article fits comfortably within the 512-token model limit.
        """
        text = path.read_text(encoding="utf-8")
        kb_id = path.stem
        version = _extract(text, r"\*\*Affected Version:\*\* (.+)")
        component = _extract(text, r"\*\*Affected Components:\*\* (.+)")

        return [{
            "id": kb_id,
            "text": text.strip(),
            "metadata": {
                "source_type": "kb_article",
                "kb_id": kb_id,
                "version": version,
                "component": component,
                "source_file": path.name,
            },
        }]

    def _chunk_product_doc(self, path: Path) -> list[dict]:
        """Split a product doc by paragraph, prepending the heading context.

        Each paragraph chunk is prefixed with "Component > Section > Subsection"
        so the retrieved chunk always carries its location in the doc hierarchy.
        """
        text = path.read_text(encoding="utf-8")
        component = _first_heading(text)

        chunks = []
        current_h2 = ""
        current_h3 = ""
        chunk_index = 0

        for block in re.split(r"\n\n+", text):
            block = block.strip()
            if not block:
                continue
            if block.startswith("# "):
                continue
            if block.startswith("## "):
                current_h2 = block.lstrip("# ").strip()
                current_h3 = ""
                continue
            if block.startswith("### "):
                current_h3 = block.lstrip("# ").strip()
                continue

            parts = [component]
            if current_h2:
                parts.append(current_h2)
            if current_h3:
                parts.append(current_h3)
            prefix = " > ".join(parts)

            chunks.append({
                "id": f"{path.stem}_c{chunk_index}",
                "text": f"{prefix}\n\n{block}",
                "metadata": {
                    "source_type": "product_doc",
                    "component": component,
                    "section": current_h2,
                    "subsection": current_h3,
                    "source_file": path.name,
                    "chunk_index": chunk_index,
                },
            })
            chunk_index += 1

        return chunks

    def _chunk_release_notes(self, path: Path) -> list[dict]:
        """Split release notes by ## section heading (What's New / Known Issues).

        Each chunk carries the version so the retriever can filter by version.
        """
        text = path.read_text(encoding="utf-8")
        version = _extract(text, r"v(\d+\.\d+(?:\.\d+)?)")
        title = _first_heading(text)

        chunks = []
        for i, (section_name, section_text) in enumerate(_split_by_h2(text)):
            chunks.append({
                "id": f"relnotes_{version.replace('.', '_')}_s{i}",
                "text": f"{title}\n\n## {section_name}\n\n{section_text}",
                "metadata": {
                    "source_type": "release_note",
                    "version": version,
                    "section": section_name,
                    "source_file": path.name,
                },
            })
        return chunks

    def _chunk_past_ticket(self, path: Path) -> list[dict]:
        """Store each past ticket as a single chunk.

        Tickets are short (~600-800 chars) and cover exactly one incident end-to-end:
        environment, symptom, diagnosis steps, and resolution. Splitting by section
        produces fragments of 150-300 chars — too short to embed meaningfully — and
        breaks the narrative context that makes tickets useful (e.g. the resolution
        only makes sense alongside the symptom and environment).
        """
        text = path.read_text(encoding="utf-8")
        ticket_id = path.stem
        version = _extract(text, r"RadVision Pro v(\S+),")
        related_kb = ",".join(re.findall(r"KB-\d+", text))

        return [{
            "id": ticket_id,
            "text": text.strip(),
            "metadata": {
                "source_type": "past_ticket",
                "ticket_id": ticket_id,
                "version": version,
                "related_kb": related_kb,
                "source_file": path.name,
            },
        }]


# ---------------------------------------------------------------------------
# Shared text utilities
# ---------------------------------------------------------------------------

def _first_heading(text: str) -> str:
    """Return the text of the first # heading, or empty string."""
    m = re.search(r"^# (.+)", text, re.MULTILINE)
    return m.group(1).strip() if m else ""


def _extract(text: str, pattern: str) -> str:
    """Return the first capture group of pattern, or 'unknown'."""
    m = re.search(pattern, text)
    return m.group(1).strip() if m else "unknown"


def _split_by_h2(text: str) -> list[tuple[str, str]]:
    """Split a markdown document into (section_name, section_body) pairs by ## headings.

    Skips the preamble before the first ## heading (title + metadata block).
    Empty sections are dropped.
    """
    parts = re.split(r"\n## ", text)
    results = []
    for part in parts[1:]:  # skip preamble
        lines = part.split("\n", 1)
        name = lines[0].strip()
        body = lines[1].strip() if len(lines) > 1 else ""
        if body:
            results.append((name, body))
    return results
